// <auto-generated />
using System;
using Administration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Administration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Administration.Models.Competence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competences");
                });

            modelBuilder.Entity("Administration.Models.Cv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OffreId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Cv", (string)null);
                });

            modelBuilder.Entity("Administration.Models.CvCompetence", b =>
                {
                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<int>("CompetenceId")
                        .HasColumnType("int");

                    b.HasKey("CvId", "CompetenceId");

                    b.HasIndex("CompetenceId");

                    b.ToTable("CvCompetences");
                });

            modelBuilder.Entity("Administration.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departement", (string)null);
                });

            modelBuilder.Entity("Administration.Models.DonneesCv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomCandidat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CvId")
                        .IsUnique();

                    b.ToTable("DonneesCvs");
                });

            modelBuilder.Entity("Administration.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CompetenceScore")
                        .HasColumnType("real");

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<float>("DiplomeScore")
                        .HasColumnType("real");

                    b.Property<float>("ExperienceScore")
                        .HasColumnType("real");

                    b.Property<float>("GlobalScore")
                        .HasColumnType("real");

                    b.Property<int>("OffreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("OffreId");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("Administration.Models.OffreEmploi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("IdResponsable")
                        .HasColumnType("int");

                    b.Property<string>("NiveauEducation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResponsableRHId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableRHId");

                    b.ToTable("OffreEmploi", (string)null);
                });

            modelBuilder.Entity("Administration.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDerniereConnexion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MotPasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateur", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            IsActive = true,
                            MotPasse = "$2a$11$8K1pQYlG9lYk1ExampleHashReplaceThis1234567890",
                            NomUtilisateur = "admin",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Administration.Models.Cv", b =>
                {
                    b.HasOne("Administration.Models.OffreEmploi", "Offre")
                        .WithMany("Cvs")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Administration.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Offre");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Administration.Models.CvCompetence", b =>
                {
                    b.HasOne("Administration.Models.Competence", "Competence")
                        .WithMany("CvCompetences")
                        .HasForeignKey("CompetenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Administration.Models.Cv", "Cv")
                        .WithMany("CvCompetences")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competence");

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("Administration.Models.DonneesCv", b =>
                {
                    b.HasOne("Administration.Models.Cv", "Cv")
                        .WithOne("DonneesCv")
                        .HasForeignKey("Administration.Models.DonneesCv", "CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");
                });

            modelBuilder.Entity("Administration.Models.Match", b =>
                {
                    b.HasOne("Administration.Models.Cv", "Cv")
                        .WithMany("Matches")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Administration.Models.OffreEmploi", "Offre")
                        .WithMany()
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("Administration.Models.OffreEmploi", b =>
                {
                    b.HasOne("Administration.Models.Utilisateur", "ResponsableRH")
                        .WithMany()
                        .HasForeignKey("ResponsableRHId");

                    b.Navigation("ResponsableRH");
                });

            modelBuilder.Entity("Administration.Models.Competence", b =>
                {
                    b.Navigation("CvCompetences");
                });

            modelBuilder.Entity("Administration.Models.Cv", b =>
                {
                    b.Navigation("CvCompetences");

                    b.Navigation("DonneesCv");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Administration.Models.OffreEmploi", b =>
                {
                    b.Navigation("Cvs");
                });
#pragma warning restore 612, 618
        }
    }
}
